apiVersion: v1
appVersion: "latest"
description: Mastodon Twitter Crossposter
name: mastodon-twitter-poster
version: 0.1.0
keywords:
  - twitter
  - mastodon
home: https://github.com/renatolond/mastodon-twitter-poster
sources:
  - https://github.com/renatolond/mastodon-twitter-poster
  - https://hub.docker.com/r/halkeye/mastodon-twitter-poster
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
